### ISSUE TITLE
Can't convert one gp, but if i export gp as gp5 then it works

### ISSUE THREAD

**Issue by DivannKokos** [rageagainsthepc/GuitarPro-to-Midi#14]
Hi again,
Whole thing worked perfectly fine until now,
One gp file (just some tab from ultimateguitar dot com + i change tuning to 7 string Drop-A)
Not converting
But if i export gp as gp5 file then it converts 
-v:
```
Error: Object reference not set to an instance of an object.
   at GP6File.transferBeat(Node node, Int32 index, Voice voice)
   at GP6File.transferVoice(Node node, Int32 index, Measure bar)
   at GP6File.transferBars(Node node, GP5File song)
   at GP6File.GP6NodeToGP5File(Node node)
   at GP7File.readSong()
   at GuitarProToMidi.GpFileParser.CreateMidiFile()
   at GuitarProToMidi.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at GuitarProToMidi.Program.Main(String[] args)
```

I also getting some other messages, but i don't think that they not connect to issue cause even if gp file successfully convert it still print this messages
messages like
```
transferNote Unrecognized node property: Midi
transferNote Unrecognized node property: TransposedPitch
transferBeat Unrecognized node property: PrimaryPickupVolume
transferBeat Unrecognized node property: PrimaryPickupTone
transferNote Unrecognized node property: ConcertPitch
```
but much much more, i mean huge portion of messages is same

**Comment by DivannKokos** [comment]
[gp file](https://drive.google.com/file/d/1cv9xvnUuD6v-zP3yYWDdLcVQ2wzbKrm0/view?usp=sharing)

**Comment by DivannKokos** [comment]
also: i think it would be great, if there was an option, to output the -verbose log not to the console, but to a txt file which is created in the location of the file you are converting
just to not flood console

**Comment by DivannKokos** [comment]
and another also: please if possible add an option that if track containing word "Bass" 
it transposes all the notes on this track a one octave up
it can be done of course when you are importing midi in daw or whatever, but just small automating thing)

**Comment by rageagainsthepc** [comment]
Thanks for the test file, I'll have a look.

> also: i think it would be great, if there was an option, to output the -verbose log not to the console, but to a txt file or whatever file which is created in the location of the file you are converting
just to not flood console

You are on Windows, right? In Powershell you could do something like this:
```powershell
PS C:\Users\RandomUser> GuitarProToMidi.exe -v .\some\file.gp | Out-File -FilePath C:\File.txt -Append
```

> and another also: please if possible add an option that if name of a track containing word "Bass"
it transposes all the notes on this track a one octave up
it can be done of course when you are importing midi in daw or whatever, but just small automating thing)

I'm afraid altering the tracks is out of the scope of this project since it aims to be a simple conversion tool. Also, that's a very specific request. I don't see a general use case for it.

**Comment by DivannKokos** [comment]
> You are on Windows, right? In Powershell you could do something like this:
> 
> ```powershell
> PS C:\Users\RandomUser> GuitarProToMidi.exe -v .\some\file.gp | Out-File -FilePath .\log.txt -Append
> ```

thanks, yes i am on windows, using powershell already, even don't know why, just for some reason installed a some time ago, powershell 7 preview



> I'm afraid altering the tracks is out of the scope of this project since it aims to be a simple conversion tool. Also, that's a very specific request. I don't see a general use case for it.

okay, i understand

**Comment by DivannKokos** [comment]
```
Error: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GP6File.transferBars(Node node, GP5File song)
   at GP6File.GP6NodeToGP5File(Node node)
   at GP7File.readSong()
   at GuitarProToMidi.GpFileParser.CreateMidiFile()
   at GuitarProToMidi.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at GuitarProToMidi.Program.Main(String[] args)
```

I got another error, with another file, it is again file from ultimate-guitar dot com + guitar tuned to 7string drop-a (notes as previous not changed, only internal tuning)
[file](https://drive.google.com/file/d/1Zvr-NEOZoOs_AI7gEYMsmZsQRfOMlIrD/view?usp=sharing)
