### ISSUE TITLE
Unable to convert on Windows 11

### ISSUE THREAD

**Issue by Turak64** [rageagainsthepc/GuitarPro-to-Midi#31]
Hi all

I'm sure I'm doing something silly here, but I just can't get this to run. Everytime I try to convert a file, I get the error "Input string was not in a correct format". I've tried a few ways, but still can't get it to work. Any help would be greatly appreciated!

![image](https://github.com/rageagainsthepc/GuitarPro-to-Midi/assets/174727457/e184fe0d-ce91-40d5-a37b-16bb69bf8292)

**Comment by DivannKokos** [comment]
try to convert gp5 file, though i think program was able to convert gp file, but just to be sure, try gp5

**Comment by DivannKokos** [comment]
yeah gp files should work... idk, try maybe drag n dropping gp file into exe file

**Comment by Turak64** [comment]
Tried both, drag & drop and CMD and got the same issue. In PS/CMD what's the exact command you're using?
![image](https://github.com/rageagainsthepc/GuitarPro-to-Midi/assets/174727457/fd4199ea-935b-4209-a83d-c598b9c07548)

**Comment by DivannKokos** [comment]
quite strange, i usually drag n dropping files
are you sure file is not corrupted in some way?

**Comment by Turak64** [comment]
I can open the same file in Guitar Pro and convert it to Midi that way. Just would be nice to use this tool instead.

**Comment by rageagainsthepc** [comment]
This does not look like an issue with commandline arguments. I would retry with the `--verbose` flag enabled if I were you. This should give you a stacktrace pointing to the source of the error.

**Comment by cirbani** [comment]
Same error here on win 10

![fdsgjfgjdgfjfj](https://github.com/user-attachments/assets/a622325e-a7cf-437a-9ee2-739963b8eede)

**Comment by cirbani** [comment]
if this helps somehow...
![gdsfjsgjsfgjgfj](https://github.com/user-attachments/assets/300aa0a0-d299-42f9-8404-dfc116a6358b)

**Comment by 11BelowStudio** [comment]
I'm also getting the same issue (on Windows 10). Here's the stack trace:
```
PS E:\blah> ./GuitarProToMidi.exe ./Reflejo.gp -v
Error: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String , IFormatProvider )
   at GuitarProToMidi.GP6File.transferTracks(Node nTracks, GP5File song)
   at GuitarProToMidi.GP6File.GP6NodeToGP5File(Node node)
   at GuitarProToMidi.GP7File.readSong()
   at GuitarProToMidi.GpFileParser.CreateMidiFile()
   at GuitarProToMidi.Program.<>c__DisplayClass0_0.<Main>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at GuitarProToMidi.Program.Main(String[] args)
```

**Comment by Metaphysics0** [comment]
problem persisting on MacOS also, example file - https://drive.google.com/file/d/1MD0P_yme4W04b-9hbx92k00vQwWYkcim/view?usp=sharing
